-- Schema para H2 - Driver Licenses
-- Tabla principal de solicitudes de licencias de conducción

DROP TABLE IF EXISTS DRIVER_LICENSES;

CREATE TABLE DRIVER_LICENSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_ID VARCHAR(20) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    HAS_SEVERE_EYE_DISABILITY BOOLEAN NOT NULL DEFAULT FALSE,
    HAS_HEARING_DISABILITY BOOLEAN NOT NULL DEFAULT FALSE,
    SERIOUS_CRIMINAL_RECORDS INT NOT NULL DEFAULT 0,
    LICENSE_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    REJECTION_REASON VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Índices para búsquedas frecuentes
CREATE INDEX IDX_DOCUMENT_ID ON DRIVER_LICENSES(DOCUMENT_ID);
CREATE INDEX IDX_STATUS ON DRIVER_LICENSES(STATUS);
CREATE INDEX IDX_LICENSE_TYPE ON DRIVER_LICENSES(LICENSE_TYPE);
